routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Андрей ---------------------------------------------------------------------------

Route::get('/link', function () {
    return view('Link');
});

//Auth::routes();
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->middleware('confirm');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/twoFactor', 'Auth\LoginController@TwoFactor');
//Route::get('/TwoFactor', 'Auth\LoginController@TwoFactor');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register')->middleware('loginCheck');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('resetPassword', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::put('updatePassword', 'Auth\ResetPasswordController@reset');
Route::get('/resetToken/{path}', 'Auth\ForgotPasswordController@checkToken');
Route::get('/resetToken', function () {
    return view('formToken');
});
/*Route::get('/resetPassword', function () {
    return view('resetPassword');
});*/
//formToken
Route::post('/resetToken', 'Auth\ForgotPasswordController@checkPhoneToken');

Route::get('/home', 'HomeController@index')->name('home');\
Route::get('/findForm',function () {
        return view('findForm');
    });
Route::get('/find','MasterController@search');
Route::resource('service', 'ServiceController');
Route::post('service/put/{id}', 'ServiceController@updatePost');
Route::resource('category', 'CategoryController');
Route::get('category/{master_id}/{cat_id}','CategoryController@showCurrent');
Route::get('service/one/{id}','ServiceController@showOne');
Route::resource('brand','BrandController');
Route::resource('email','EmailController');
Route::resource('phone','PhoneController');

Route::put('profile/{id}','ProfileController@update');

/*VerificationController Begin*/
Route::get('/addNewToken', 'VerificationController@addNewToken');
/*Mobile*/
Route::get('/sendToken', 'VerificationController@sendToken');
Route::get('/addNewMobileToken', 'VerificationController@addNewMobileToken');
/*Mobile END*/
Route::get('/role/{role}', 'VerificationController@chooseRole');
Route::get('/verification/{path}', 'VerificationController@verification')/*->middleware('roleCheck')*/;
Route::post('/verification', 'VerificationController@verificationPhone');
Route::get('/verification',function () {
    return view('verification');
});
/*VerificationController End*/


//Славик------------------------------------------------------------------------------

//Главная страница---------------------------------------------------------------------
Route::get('/', function () {
    return view('index');
})->name('main');

//Регистрация(аунтификация) через соц. сети------------------------------------------
Route::get('/login/{provider}', ['uses'=>'SocialController@login','as'=>'social_login']);

Route::get('/callback_login/{provider}', ['uses'=>'SocialController@callback','as'=>'social_callback']);



Route::group(['prefix'=>'user'], function(){

    //Получить профиль пользователя----------------------------------------------
    Route::get('current', ['uses'=>'ProfileController@index','as'=>'profile']);
    Route::get('/{id}', ['uses'=>'ProfileController@index', 'as'=>'prof']);
    //Включить(отключить) двухфакторную верификацию
    Route::put('/user/{id}/factor','ProfileController@factor');
});

// Мастер,
    Route::get('master/{id}/gallery', ['uses'=>'GalleryController@index', 'as'=>'gallery.index'])->middleware('auth');

Route::group(['prefix'=>'master/{id}', 'middleware' => 'master'], function(){

    Route::match(['PUT'],'gallery',['uses'=>'GalleryController@update', 'as'=>'gallery.update']);
    Route::resource('gallery','GalleryController',[
        'only'=>['store','destroy']
    ]);
});




//Контролер RESTful Address---

Route::resource('user.address', 'AddressController');




//Тестирование, чтобы не мешать другим.-------------------------------------
Route::get('/user/test', ['uses'=>'ProfileController@test','as'=>'test_profile']);

//Основной тестовый контроллер (удалать в prod)---------------------------------------
Route::get('/test', 'TestController@index')->name('test');
Route::get('/t', 'TestController@test')->name('t');

resources/views/2factor.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="TwoFactor" method="post" >
                    Select image to upload:
                    {{ csrf_field() }}
                    <input name="token" id="token">
                    <input type="submit" value="Send" name="submit">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Link.blade.php
<h1>Вы не подтвердили почту . Зайдите себе на ящик</h1>
Если время истекло кликните на ссылку ниже<br>
Ссылка =)

resources/views/addBrand.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add Brand</div>
                <div class="panel-body">
                    <div class="col-md-10 ">
                        <form action="brand" method="post">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label class="col-md-4 control-label">Выбери бренд</label>
                                <div class="col-md-6">
                                    <select name="name">
                                        <option value="Бренд 1">Бренд 1</option>
                                        <option value="Бренд 2">Бренд 2</option>
                                        <option value="Бренд 3">Бренд 3</option>
                                        <option value="Бренд 4">Бренд 4</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <input name="id">
                            </div>
                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Add
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/addGallery.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="{{route('gallery.store', ['id'=>2])}}" method="post" enctype="multipart/form-data">
                    Select image to upload:
                    {{ csrf_field() }}
                    <input type="file" name="image" id="image">
                    <input type="submit" value="Upload Image" name="submit">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/addService.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add Service</div>
                <div class="panel-body">
            <div class="col-md-10 ">
                <form action="service/1" method="post" >
                    <input name="_method" type="hidden" value="PUT">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name" class="col-md-6 control-label">Name Service</label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control" name="name" >

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="priceMin" class="col-md-6 control-label">Price Min</label>

                        <div class="col-md-6">
                            <input id="priceMin" type="text" class="form-control" name="priceMin" >

                        </div>
                    </div>
                    </br>
                    <div class="form-group">
                        <label for="priceMax" class="col-md-4 control-label">Price Max</label>

                        <div class="col-md-6">
                            <input id="priceMax" type="text" class="form-control" name="priceMax" >

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="time" class="col-md-4 control-label">Time</label>

                        <div class="col-md-6">
                            <input id="time" type="text" class="form-control" name="time" >

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Add
                            </button>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
        </div>
    </div>
@endsection

resources/views/findForm.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Login</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="GET" action="find">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="city" class="col-md-4 control-label">City</label>

                                <div class="col-md-6">
                                    <input id="city" type="text" class="form-control" name="city" >
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Login
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/formToken.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="resetToken" method="post" >
                    Select image to upload:
                    {{ csrf_field() }}
                    <input name="token" id="token">
                    <input type="submit" value="Send" name="submit">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/resetPassword.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="updatePassword" method="post" >
                    <div class="form-group">
                        <label for="password" class="col-md-4 control-label">Password</label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control" name="password" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>
                        <div class="col-md-6">
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" >
                        </div>
                    </div>
                    <input type="submit" value="Update" name="submit">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/updatePassword.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Login</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('login') }}">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="password" class="col-md-4 control-label">Password</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control" name="password" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" >
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/upload.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="upload" method="post" enctype="multipart/form-data">
                    Select image to upload:
                    {{ csrf_field() }}
                    <select name="id" id ="id">
                        <option value="0">Аватар</option>
                        <option value="1">Фон</option>
                    </select>
                    <input type="file" name="image" id="image">
                    <input type="submit" value="Upload Image" name="submit">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/verification.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="verification" method="post" >
                    Enter code from sms:
                    {{ csrf_field() }}
                    <input name="token" id="token">
                    <input type="submit" value="Send" name="submit">
                </form>

            </div>
        </div>
    </div>
@endsection